spring:
  profiles:
    active:
  application:
    name: baiduai
  jmx:
    enabled: false
  # force设置为true，response输出才采用设置charset进行编码输出
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
server: 
    port:
    tomcat: 
      uri-encoding: UTF-8
log:
  enable: true
